eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://jabranemohamed:VkOHdd43uO2JpBOo@order.yd95mwg.mongodb.net/?retryWrites=true&w=majority
     # uri: mongodb+srv://admin:codedecode@atlas-cluster.mqdj7js.mongodb.net/?retryWrites=true&w=majority # mongodb://localhost:27017/orderdb
      host: atlas-cluster.mqdj7js.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true
