apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:postgresql://flora.db.elephantsql.com:5432/fnpxehry
  foodcataloguedb_url: jdbc:postgresql://flora.db.elephantsql.com:5432/jlyuwmno
  userdb_url: jdbc:postgresql://flora.db.elephantsql.com:5432/kyjtfsco
  orderdb_url: mongodb+srv://jabranemohamed:VkOHdd43uO2JpBOo@order.yd95mwg.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka


  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
