server:
  port: 9092

spring:
  profiles:
    active: dev
  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    url: jdbc:postgresql://flora.db.elephantsql.com:5432/jlyuwmno
    username: jlyuwmno
    password: u5tDdLmd1NLEUrB56i7q-h-kz9nv1qHc
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

