eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka


spring:
  datasource:
    url: jdbc:postgresql://flora.db.elephantsql.com:5432/fnpxehry
    username: fnpxehry
    password: AGR19-sypoMAWDGY0d1b-VLXLBNIIW9F
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

